
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package main.Servidor_React.analizador;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PAR2 = 9;
  public static final int PAR1 = 8;
  public static final int FUNCTION = 33;
  public static final int POT = 2;
  public static final int CONST = 23;
  public static final int POR = 5;
  public static final int CHAR = 27;
  public static final int LLAVE2 = 19;
  public static final int EQUALS = 13;
  public static final int LLAVE1 = 18;
  public static final int ENTERO = 39;
  public static final int FOR = 36;
  public static final int IDENTIFICADOR = 41;
  public static final int FINCADENA = 17;
  public static final int AND = 15;
  public static final int IGUAL = 10;
  public static final int CARACTER = 43;
  public static final int OR = 14;
  public static final int DIV = 6;
  public static final int UMENOS = 7;
  public static final int IF = 34;
  public static final int DECIMAL = 40;
  public static final int EOF = 0;
  public static final int BOOLEAN = 28;
  public static final int RETURN = 24;
  public static final int TRUE = 37;
  public static final int error = 1;
  public static final int COMA = 21;
  public static final int CADENA = 42;
  public static final int MENOS = 4;
  public static final int MENOR = 11;
  public static final int NUMBER = 25;
  public static final int VOID = 29;
  public static final int MAYOR = 12;
  public static final int LOG = 32;
  public static final int ELSE = 35;
  public static final int PUNTO = 22;
  public static final int STRING = 26;
  public static final int DIFER = 16;
  public static final int FALSE = 38;
  public static final int VAR = 30;
  public static final int DOSPTS = 20;
  public static final int CONSOLE = 31;
  public static final int MAS = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "POT",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "UMENOS",
  "PAR1",
  "PAR2",
  "IGUAL",
  "MENOR",
  "MAYOR",
  "EQUALS",
  "OR",
  "AND",
  "DIFER",
  "FINCADENA",
  "LLAVE1",
  "LLAVE2",
  "DOSPTS",
  "COMA",
  "PUNTO",
  "CONST",
  "RETURN",
  "NUMBER",
  "STRING",
  "CHAR",
  "BOOLEAN",
  "VOID",
  "VAR",
  "CONSOLE",
  "LOG",
  "FUNCTION",
  "IF",
  "ELSE",
  "FOR",
  "TRUE",
  "FALSE",
  "ENTERO",
  "DECIMAL",
  "IDENTIFICADOR",
  "CADENA",
  "CARACTER"
  };
}

