package main;

import java.io.File;
import javax.swing.JOptionPane;
import utils.GestionArchivos;

/**
 *
 * @author marco
 */
public class editorToml extends javax.swing.JPanel {

    NumeroLinea numerolinea;
    GestionArchivos gestion = new GestionArchivos();

    /**
     * Creates new form editorToml
     */
    public editorToml(String contenido) {
        initComponents();
        
        panTom.setText(contenido);
        numerolinea = new NumeroLinea(panTom);
        conta_Scroll.setRowHeaderView(numerolinea);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        conta_Scroll = new javax.swing.JScrollPane();
        panTom = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        BT_guardar = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(33, 47, 61));

        panTom.setBackground(new java.awt.Color(46, 64, 83));
        panTom.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        panTom.setForeground(new java.awt.Color(255, 255, 255));
        conta_Scroll.setViewportView(panTom);

        jLabel1.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editor Toml");

        BT_guardar.setBackground(new java.awt.Color(46, 64, 83));
        BT_guardar.setFont(new java.awt.Font("FreeMono", 1, 18)); // NOI18N
        BT_guardar.setForeground(new java.awt.Color(255, 255, 255));
        BT_guardar.setText("Guardar");
        BT_guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BT_guardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jLabel1)
                        .addGap(121, 121, 121)
                        .addComponent(BT_guardar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(conta_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 1016, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(BT_guardar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(conta_Scroll, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BT_guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BT_guardarActionPerformed
        // TODO add your handling code here:
        guardarArchivo();
    }//GEN-LAST:event_BT_guardarActionPerformed

    private void guardarArchivo() {
        // Obtener el contenido del JTextPane
        String contenido = panTom.getText();

        // Guardar el contenido de nuevo en el archivo
        String resultado = gestion.GuardarATexto(new File("/home/marco/Documentos/Compi_2025/MINIMAL_REACT_CMS/data/recovery.toml"), contenido);

        // Mostrar un mensaje de confirmación
        JOptionPane.showMessageDialog(this, resultado);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BT_guardar;
    private javax.swing.JScrollPane conta_Scroll;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextPane panTom;
    // End of variables declaration//GEN-END:variables
}
